import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { computeTermsContentHash, parseGitPage } from "./git.server";

const repositorySource = readFileSync(new URL("./git.server.ts", import.meta.url), "utf8");
const generatedSource = readFileSync(new URL("./generated-pages.ts", import.meta.url), "utf8");
const generatorSource = readFileSync(
  new URL("../../../scripts/generate-content-pages.mjs", import.meta.url),
  "utf8",
);

test("Git pages are loaded from a committed build artifact instead of runtime filesystem access", () => {
  assert.match(repositorySource, /from "\.\/generated-pages"/);
  assert.match(repositorySource, /GIT_PAGE_SOURCES\[slug\]/);
  assert.equal(/node:fs|process\.cwd|readFile\(/.test(repositorySource), false);
  assert.match(generatedSource, /Generated by scripts\/generate-content-pages\.mjs/);
});

test("content generator is allowlisted, bounded and supports a non-mutating CI check", () => {
  assert.match(generatorSource, /ALLOWED_PAGE_SLUGS/);
  assert.match(generatorSource, /MAX_FILE_BYTES/);
  assert.match(generatorSource, /process\.argv\.includes\("--check"\)/);
  assert.match(generatorSource, /Generated Git page artifact is stale/);
  assert.equal(/terms\.md[\s\S]*placeholder legal copy/.test(generatorSource), false);
});

test("versioned Terms parsing remains deterministic without runtime filesystem access", () => {
  const body = "متن بازبینی‌شدهٔ شرایط";
  const raw = [
    "---",
    'slug: "terms"',
    'title: "شرایط استفاده"',
    'version: "fixture-v1"',
    'seoTitle: "شرایط استفاده"',
    "seoDescription: null",
    'canonicalPath: "/terms"',
    'robots: "noindex"',
    "---",
    "",
    body,
  ].join("\n");

  const page = parseGitPage(raw, "terms");
  assert.ok(page);
  assert.equal(page.version, "fixture-v1");
  assert.equal(page.contentHash, computeTermsContentHash("fixture-v1", body));
  assert.match(page.contentHash ?? "", /^[0-9a-f]{64}$/);
});
