// Generated by scripts/generate-content-pages.mjs. Do not edit by hand.
export interface TermsRelease {
  readonly version: string;
  readonly currentContentHash: string;
  readonly allowedContentHashes: readonly string[];
}

export const CURRENT_TERMS_RELEASE: TermsRelease | null = null;
