/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildingStoneRouteImport } from './routes/building-stone'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as StoneworksRouteImport } from './routes/stoneworks'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiSubmitRequestRouteImport } from './routes/api/submit-request'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnBuildingStoneRouteImport } from './routes/en/building-stone'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnPortfolioRouteImport } from './routes/en/portfolio'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as EnQuoteRouteImport } from './routes/en/quote'
import { Route as EnStoneworksRouteImport } from './routes/en/stoneworks'
import { Route as EnTermsRouteImport } from './routes/en/terms'
import { Route as GraveStonesIndexRouteImport } from './routes/grave-stones/index'
import { Route as GraveStonesSlugRouteImport } from './routes/grave-stones/$slug'
import { Route as GraveStonesCustomRouteImport } from './routes/grave-stones/custom'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as EnGraveStonesIndexRouteImport } from './routes/en/grave-stones/index'
import { Route as EnGraveStonesSlugRouteImport } from './routes/en/grave-stones/$slug'
import { Route as EnGraveStonesCustomRouteImport } from './routes/en/grave-stones/custom'
import { Route as EnGuidesIndexRouteImport } from './routes/en/guides/index'
import { Route as EnGuidesSlugRouteImport } from './routes/en/guides/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingStoneRoute = BuildingStoneRouteImport.update({
  id: '/building-stone',
  path: '/building-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneworksRoute = StoneworksRouteImport.update({
  id: '/stoneworks',
  path: '/stoneworks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitRequestRoute = ApiSubmitRequestRouteImport.update({
  id: '/api/submit-request',
  path: '/api/submit-request',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBuildingStoneRoute = EnBuildingStoneRouteImport.update({
  id: '/en/building-stone',
  path: '/en/building-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPortfolioRoute = EnPortfolioRouteImport.update({
  id: '/en/portfolio',
  path: '/en/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnQuoteRoute = EnQuoteRouteImport.update({
  id: '/en/quote',
  path: '/en/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStoneworksRoute = EnStoneworksRouteImport.update({
  id: '/en/stoneworks',
  path: '/en/stoneworks',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/en/terms',
  path: '/en/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GraveStonesIndexRoute = GraveStonesIndexRouteImport.update({
  id: '/grave-stones/',
  path: '/grave-stones/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraveStonesSlugRoute = GraveStonesSlugRouteImport.update({
  id: '/grave-stones/$slug',
  path: '/grave-stones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GraveStonesCustomRoute = GraveStonesCustomRouteImport.update({
  id: '/grave-stones/custom',
  path: '/grave-stones/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGraveStonesIndexRoute = EnGraveStonesIndexRouteImport.update({
  id: '/en/grave-stones/',
  path: '/en/grave-stones/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGraveStonesSlugRoute = EnGraveStonesSlugRouteImport.update({
  id: '/en/grave-stones/$slug',
  path: '/en/grave-stones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGraveStonesCustomRoute = EnGraveStonesCustomRouteImport.update({
  id: '/en/grave-stones/custom',
  path: '/en/grave-stones/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGuidesIndexRoute = EnGuidesIndexRouteImport.update({
  id: '/en/guides/',
  path: '/en/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGuidesSlugRoute = EnGuidesSlugRouteImport.update({
  id: '/en/guides/$slug',
  path: '/en/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-stone': typeof BuildingStoneRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/stoneworks': typeof StoneworksRoute
  '/terms': typeof TermsRoute
  '/api/submit-request': typeof ApiSubmitRequestRoute
  '/en/about': typeof EnAboutRoute
  '/en/building-stone': typeof EnBuildingStoneRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/quote': typeof EnQuoteRoute
  '/en/stoneworks': typeof EnStoneworksRoute
  '/en/terms': typeof EnTermsRoute
  '/grave-stones/$slug': typeof GraveStonesSlugRoute
  '/grave-stones/custom': typeof GraveStonesCustomRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/grave-stones/': typeof GraveStonesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/en/grave-stones/$slug': typeof EnGraveStonesSlugRoute
  '/en/grave-stones/custom': typeof EnGraveStonesCustomRoute
  '/en/guides/$slug': typeof EnGuidesSlugRoute
  '/en/grave-stones/': typeof EnGraveStonesIndexRoute
  '/en/guides/': typeof EnGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-stone': typeof BuildingStoneRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/stoneworks': typeof StoneworksRoute
  '/terms': typeof TermsRoute
  '/api/submit-request': typeof ApiSubmitRequestRoute
  '/en/about': typeof EnAboutRoute
  '/en/building-stone': typeof EnBuildingStoneRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/quote': typeof EnQuoteRoute
  '/en/stoneworks': typeof EnStoneworksRoute
  '/en/terms': typeof EnTermsRoute
  '/grave-stones/$slug': typeof GraveStonesSlugRoute
  '/grave-stones/custom': typeof GraveStonesCustomRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en': typeof EnIndexRoute
  '/grave-stones': typeof GraveStonesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/en/grave-stones/$slug': typeof EnGraveStonesSlugRoute
  '/en/grave-stones/custom': typeof EnGraveStonesCustomRoute
  '/en/guides/$slug': typeof EnGuidesSlugRoute
  '/en/grave-stones': typeof EnGraveStonesIndexRoute
  '/en/guides': typeof EnGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/building-stone': typeof BuildingStoneRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/stoneworks': typeof StoneworksRoute
  '/terms': typeof TermsRoute
  '/api/submit-request': typeof ApiSubmitRequestRoute
  '/en/about': typeof EnAboutRoute
  '/en/building-stone': typeof EnBuildingStoneRoute
  '/en/contact': typeof EnContactRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/quote': typeof EnQuoteRoute
  '/en/stoneworks': typeof EnStoneworksRoute
  '/en/terms': typeof EnTermsRoute
  '/grave-stones/$slug': typeof GraveStonesSlugRoute
  '/grave-stones/custom': typeof GraveStonesCustomRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/grave-stones/': typeof GraveStonesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/en/grave-stones/$slug': typeof EnGraveStonesSlugRoute
  '/en/grave-stones/custom': typeof EnGraveStonesCustomRoute
  '/en/guides/$slug': typeof EnGuidesSlugRoute
  '/en/grave-stones/': typeof EnGraveStonesIndexRoute
  '/en/guides/': typeof EnGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/building-stone'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/stoneworks'
    | '/terms'
    | '/api/submit-request'
    | '/en/about'
    | '/en/building-stone'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/privacy'
    | '/en/quote'
    | '/en/stoneworks'
    | '/en/terms'
    | '/grave-stones/$slug'
    | '/grave-stones/custom'
    | '/guides/$slug'
    | '/en/'
    | '/grave-stones/'
    | '/guides/'
    | '/en/grave-stones/$slug'
    | '/en/grave-stones/custom'
    | '/en/guides/$slug'
    | '/en/grave-stones/'
    | '/en/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/building-stone'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/stoneworks'
    | '/terms'
    | '/api/submit-request'
    | '/en/about'
    | '/en/building-stone'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/privacy'
    | '/en/quote'
    | '/en/stoneworks'
    | '/en/terms'
    | '/grave-stones/$slug'
    | '/grave-stones/custom'
    | '/guides/$slug'
    | '/en'
    | '/grave-stones'
    | '/guides'
    | '/en/grave-stones/$slug'
    | '/en/grave-stones/custom'
    | '/en/guides/$slug'
    | '/en/grave-stones'
    | '/en/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/building-stone'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/stoneworks'
    | '/terms'
    | '/api/submit-request'
    | '/en/about'
    | '/en/building-stone'
    | '/en/contact'
    | '/en/portfolio'
    | '/en/privacy'
    | '/en/quote'
    | '/en/stoneworks'
    | '/en/terms'
    | '/grave-stones/$slug'
    | '/grave-stones/custom'
    | '/guides/$slug'
    | '/en/'
    | '/grave-stones/'
    | '/guides/'
    | '/en/grave-stones/$slug'
    | '/en/grave-stones/custom'
    | '/en/guides/$slug'
    | '/en/grave-stones/'
    | '/en/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildingStoneRoute: typeof BuildingStoneRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  StoneworksRoute: typeof StoneworksRoute
  TermsRoute: typeof TermsRoute
  ApiSubmitRequestRoute: typeof ApiSubmitRequestRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBuildingStoneRoute: typeof EnBuildingStoneRoute
  EnContactRoute: typeof EnContactRoute
  EnPortfolioRoute: typeof EnPortfolioRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnQuoteRoute: typeof EnQuoteRoute
  EnStoneworksRoute: typeof EnStoneworksRoute
  EnTermsRoute: typeof EnTermsRoute
  GraveStonesSlugRoute: typeof GraveStonesSlugRoute
  GraveStonesCustomRoute: typeof GraveStonesCustomRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  GraveStonesIndexRoute: typeof GraveStonesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  EnGraveStonesSlugRoute: typeof EnGraveStonesSlugRoute
  EnGraveStonesCustomRoute: typeof EnGraveStonesCustomRoute
  EnGuidesSlugRoute: typeof EnGuidesSlugRoute
  EnGraveStonesIndexRoute: typeof EnGraveStonesIndexRoute
  EnGuidesIndexRoute: typeof EnGuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-stone': {
      id: '/building-stone'
      path: '/building-stone'
      fullPath: '/building-stone'
      preLoaderRoute: typeof BuildingStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoneworks': {
      id: '/stoneworks'
      path: '/stoneworks'
      fullPath: '/stoneworks'
      preLoaderRoute: typeof StoneworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-request': {
      id: '/api/submit-request'
      path: '/api/submit-request'
      fullPath: '/api/submit-request'
      preLoaderRoute: typeof ApiSubmitRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/building-stone': {
      id: '/en/building-stone'
      path: '/en/building-stone'
      fullPath: '/en/building-stone'
      preLoaderRoute: typeof EnBuildingStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/portfolio': {
      id: '/en/portfolio'
      path: '/en/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof EnPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/quote': {
      id: '/en/quote'
      path: '/en/quote'
      fullPath: '/en/quote'
      preLoaderRoute: typeof EnQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stoneworks': {
      id: '/en/stoneworks'
      path: '/en/stoneworks'
      fullPath: '/en/stoneworks'
      preLoaderRoute: typeof EnStoneworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/en/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grave-stones/': {
      id: '/grave-stones/'
      path: '/grave-stones'
      fullPath: '/grave-stones/'
      preLoaderRoute: typeof GraveStonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grave-stones/$slug': {
      id: '/grave-stones/$slug'
      path: '/grave-stones/$slug'
      fullPath: '/grave-stones/$slug'
      preLoaderRoute: typeof GraveStonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grave-stones/custom': {
      id: '/grave-stones/custom'
      path: '/grave-stones/custom'
      fullPath: '/grave-stones/custom'
      preLoaderRoute: typeof GraveStonesCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/grave-stones/': {
      id: '/en/grave-stones/'
      path: '/en/grave-stones'
      fullPath: '/en/grave-stones/'
      preLoaderRoute: typeof EnGraveStonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/grave-stones/$slug': {
      id: '/en/grave-stones/$slug'
      path: '/en/grave-stones/$slug'
      fullPath: '/en/grave-stones/$slug'
      preLoaderRoute: typeof EnGraveStonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/grave-stones/custom': {
      id: '/en/grave-stones/custom'
      path: '/en/grave-stones/custom'
      fullPath: '/en/grave-stones/custom'
      preLoaderRoute: typeof EnGraveStonesCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/guides/': {
      id: '/en/guides/'
      path: '/en/guides'
      fullPath: '/en/guides/'
      preLoaderRoute: typeof EnGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/guides/$slug': {
      id: '/en/guides/$slug'
      path: '/en/guides/$slug'
      fullPath: '/en/guides/$slug'
      preLoaderRoute: typeof EnGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildingStoneRoute: BuildingStoneRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  StoneworksRoute: StoneworksRoute,
  TermsRoute: TermsRoute,
  ApiSubmitRequestRoute: ApiSubmitRequestRoute,
  EnAboutRoute: EnAboutRoute,
  EnBuildingStoneRoute: EnBuildingStoneRoute,
  EnContactRoute: EnContactRoute,
  EnPortfolioRoute: EnPortfolioRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnQuoteRoute: EnQuoteRoute,
  EnStoneworksRoute: EnStoneworksRoute,
  EnTermsRoute: EnTermsRoute,
  GraveStonesSlugRoute: GraveStonesSlugRoute,
  GraveStonesCustomRoute: GraveStonesCustomRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  EnIndexRoute: EnIndexRoute,
  GraveStonesIndexRoute: GraveStonesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  EnGraveStonesSlugRoute: EnGraveStonesSlugRoute,
  EnGraveStonesCustomRoute: EnGraveStonesCustomRoute,
  EnGuidesSlugRoute: EnGuidesSlugRoute,
  EnGraveStonesIndexRoute: EnGraveStonesIndexRoute,
  EnGuidesIndexRoute: EnGuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
